nxp-ls1028: remove meta-qoriq from LAYERDEPENDS
Issue: LINUXEXEC-27724

When building WRLinux project, there is below ERROR
ERROR: Layer 'wr-nxp-ls1028' depends on layer 'meta-qoriq',
but this layer is not enabled in your configuration
Because the meta-qoriq layer is still not integrated into WRLinux product,
remove meta-qoriq from LAYERDEPENDS.

Signed-off-by: Meng Li <Meng.Li@windriver.com>